# -*- coding: utf-8 -*-

SURFACE = '#061b24'
PANEL = '#0d2f3a'
PANEL_ALT = '#143d4a'
PANEL_RAISED = '#1c5966'
BORDER = '#2e7e8f'
ACCENT = '#6ef56a'
ACCENT_HOVER = '#9dff78'
MUTED = '#a8dde2'
SUCCESS = ACCENT
WARNING = '#ffd45a'

WINDOW = SURFACE

TEXT = '#f5fff9'
TEXT_DISABLED = '#7199a0'
TEXT_MUTED = MUTED
TEXT_ERROR = '#ff8a7a'

BORDER_LIGHT = '#1f5663'
BORDER_DARK = BORDER
BORDER_FOCUS = '#3ddcff'

LINE_EDIT = '#08232c'
PLAIN_EDIT = '#06161c'
COMBOBOX = '#0b3340'

BUTTON = '#103c49'
BUTTON_HOVER = '#16596b'
BUTTON_PRESSED = '#092a34'
BUTTON_DISABLED = '#102b34'
BUTTON_DEFAULT = '#18b9f2'
BUTTON_DEFAULT_HOVER = '#55d7ff'

SCROLLBAR = '#2b7686'
SCROLLBAR_HOVER = '#44a6b9'

SELECTION = '#0f6f86'
SELECTION_TEXT = TEXT

TAB_INACTIVE = SURFACE
TAB_ACTIVE = PANEL
TAB_ACTIVE_BORDER = ACCENT

TRANSLATED_TABLEVIEW = '#071a22'
TRANSLATED_TABLEVIEW_ODD = '#0a222c'
TRANSLATED_BAR = BORDER_FOCUS

VALIDATED_TABLEVIEW = '#0c3a34'
VALIDATED_TABLEVIEW_ODD = '#10463e'
VALIDATED_BAR = SUCCESS

PROGRESS_TABLEVIEW = '#40371a'
PROGRESS_TABLEVIEW_ODD = '#4d421f'
PROGRESS_BAR = WARNING

UNVALIDATED_TABLEVIEW = '#18323c'
UNVALIDATED_TABLEVIEW_ODD = '#203f49'
UNVALIDATED_BAR = '#d6c76a'

DIFFERENT_TABLEVIEW = '#3d3220'
DIFFERENT_TABLEVIEW_ODD = '#4b3e29'

PROGRESSBAR = '#08252f'

EDITOR_LINES = '#102f38'
EDITOR_LINES_TEXT = TEXT_MUTED
EDITOR_LINES_BORDER = BORDER_LIGHT

EDITOR_LINE = PANEL
EDITOR_BRACKET = '#2f8795'

EDITOR_SIMNAME = SUCCESS
EDITOR_SIMNAME_BOLD = False

EDITOR_MALE = BORDER_FOCUS
EDITOR_MALE_BOLD = False

EDITOR_FEMALE = '#f4a7df'
EDITOR_FEMALE_BOLD = False

EDITOR_VAR_BOLD = True

EDITOR_TAG = TEXT_MUTED

HEADER = PANEL_ALT

FONT_SANS = "Roboto, 'Segoe UI', sans-serif"
FONT_MONOSPACE = "'JetBrains Mono', Consolas, 'Courier New', monospace"
