# -*- coding: utf-8 -*-

SURFACE = '#041814'
PANEL = '#0b2f27'
PANEL_ALT = '#123f33'
PANEL_RAISED = '#205f4a'
BORDER = '#55ac88'
ACCENT = '#a9f76b'
ACCENT_HOVER = '#d3ff9a'
MUTED = '#c4e7d0'
SUCCESS = ACCENT
WARNING = '#ffd96a'

WINDOW = SURFACE

TEXT = '#f8fff4'
TEXT_DISABLED = '#7f9d8f'
TEXT_MUTED = MUTED
TEXT_ERROR = '#ff8a7a'

BORDER_LIGHT = '#2d6b55'
BORDER_DARK = BORDER
BORDER_FOCUS = '#72f4d8'

LINE_EDIT = '#06221c'
PLAIN_EDIT = '#03130f'
COMBOBOX = '#0b352b'

BUTTON = '#103d30'
BUTTON_HOVER = '#1f674f'
BUTTON_PRESSED = '#08281f'
BUTTON_DISABLED = '#102b23'
BUTTON_DEFAULT = '#9bf26a'
BUTTON_DEFAULT_HOVER = '#c8ff88'

SCROLLBAR = '#429578'
SCROLLBAR_HOVER = '#65bd98'

SELECTION = '#1d775c'
SELECTION_TEXT = TEXT

TAB_INACTIVE = SURFACE
TAB_ACTIVE = PANEL
TAB_ACTIVE_BORDER = ACCENT

TRANSLATED_TABLEVIEW = '#05201a'
TRANSLATED_TABLEVIEW_ODD = '#082820'
TRANSLATED_BAR = BORDER_FOCUS

VALIDATED_TABLEVIEW = '#0f3a28'
VALIDATED_TABLEVIEW_ODD = '#164d34'
VALIDATED_BAR = SUCCESS

PROGRESS_TABLEVIEW = '#403a1f'
PROGRESS_TABLEVIEW_ODD = '#4d4624'
PROGRESS_BAR = WARNING

UNVALIDATED_TABLEVIEW = '#233c2b'
UNVALIDATED_TABLEVIEW_ODD = '#2d4b34'
UNVALIDATED_BAR = '#d8d66a'

DIFFERENT_TABLEVIEW = '#3b3221'
DIFFERENT_TABLEVIEW_ODD = '#493f2c'

PROGRESSBAR = '#08241d'

EDITOR_LINES = '#102d24'
EDITOR_LINES_TEXT = TEXT_MUTED
EDITOR_LINES_BORDER = BORDER_LIGHT

EDITOR_LINE = PANEL
EDITOR_BRACKET = '#4ca18a'

EDITOR_SIMNAME = SUCCESS
EDITOR_SIMNAME_BOLD = False

EDITOR_MALE = BORDER_FOCUS
EDITOR_MALE_BOLD = False

EDITOR_FEMALE = '#f4a7df'
EDITOR_FEMALE_BOLD = False

EDITOR_VAR_BOLD = True

EDITOR_TAG = TEXT_MUTED

HEADER = PANEL_ALT

FONT_SANS = "Roboto, 'Segoe UI', sans-serif"
FONT_MONOSPACE = "'JetBrains Mono', Consolas, 'Courier New', monospace"
