# -*- coding: utf-8 -*-

SURFACE = '#121820'
PANEL = '#192331'
PANEL_ALT = '#14202b'
PANEL_RAISED = '#203044'
BORDER = '#2d4356'
ACCENT = '#62b6ff'
ACCENT_HOVER = '#8ac8ff'
MUTED = '#92a8b8'
SUCCESS = '#5fd6a2'
WARNING = '#f0b766'

WINDOW = SURFACE

TEXT = '#e6f0f6'
TEXT_DISABLED = '#627888'
TEXT_MUTED = MUTED
TEXT_ERROR = '#ff8580'

BORDER_LIGHT = BORDER
BORDER_DARK = '#38546a'
BORDER_FOCUS = ACCENT

LINE_EDIT = PANEL
PLAIN_EDIT = SURFACE
COMBOBOX = PANEL_RAISED

BUTTON = PANEL
BUTTON_HOVER = PANEL_RAISED
BUTTON_PRESSED = SURFACE
BUTTON_DISABLED = '#f8f8f8'
BUTTON_DEFAULT = ACCENT
BUTTON_DEFAULT_HOVER = ACCENT_HOVER

SCROLLBAR = '#2d4356'
SCROLLBAR_HOVER = '#3e6178'

SELECTION = '#174e77'
SELECTION_TEXT = TEXT

TAB_INACTIVE = PLAIN_EDIT
TAB_ACTIVE = PANEL
TAB_ACTIVE_BORDER = BORDER_DARK

TRANSLATED_TABLEVIEW = '#121820'
TRANSLATED_TABLEVIEW_ODD = '#17212d'
TRANSLATED_BAR = '#1c2c3a'

VALIDATED_TABLEVIEW = '#163354'
VALIDATED_TABLEVIEW_ODD = '#1c4068'
VALIDATED_BAR = '#62b6ff'

PROGRESS_TABLEVIEW = '#4a3320'
PROGRESS_TABLEVIEW_ODD = '#5c3f27'
PROGRESS_BAR = '#f0b766'

UNVALIDATED_TABLEVIEW = '#4f242a'
UNVALIDATED_TABLEVIEW_ODD = '#622c33'
UNVALIDATED_BAR = '#a65f68'

DIFFERENT_TABLEVIEW = '#493625'
DIFFERENT_TABLEVIEW_ODD = '#5c452f'

PROGRESSBAR = PLAIN_EDIT

EDITOR_LINES = '#26282e'
EDITOR_LINES_TEXT = TEXT_MUTED
EDITOR_LINES_BORDER = BORDER_LIGHT

EDITOR_LINE = '#26282e'
EDITOR_BRACKET = '#43454a'

EDITOR_SIMNAME = '#5fd6a2'
EDITOR_SIMNAME_BOLD = False

EDITOR_MALE = '#62b6ff'
EDITOR_MALE_BOLD = False

EDITOR_FEMALE = '#cf84cf'
EDITOR_FEMALE_BOLD = False

EDITOR_VAR_BOLD = True

EDITOR_TAG = TEXT_MUTED

HEADER = BORDER_LIGHT

FONT_SANS = "Roboto, 'Segoe UI', sans-serif"
FONT_MONOSPACE = "'JetBrains Mono', Consolas, 'Courier New', monospace"
