# -*- coding: utf-8 -*-

SURFACE = '#1e1f22'
PANEL = '#2b2d30'
PANEL_ALT = '#25262b'
PANEL_RAISED = '#303238'
BORDER = '#3f424a'
ACCENT = '#7aa2f7'
ACCENT_HOVER = '#8bb0ff'
MUTED = '#8b909a'
SUCCESS = '#73bd79'
WARNING = '#d6a85a'

WINDOW = SURFACE

TEXT = '#dfe1e5'
TEXT_DISABLED = '#5a5d63'
TEXT_MUTED = MUTED
TEXT_ERROR = '#de6a66'

BORDER_LIGHT = BORDER
BORDER_DARK = '#4e5157'
BORDER_FOCUS = ACCENT

LINE_EDIT = PANEL
PLAIN_EDIT = SURFACE
COMBOBOX = PANEL_RAISED

BUTTON = PANEL
BUTTON_HOVER = PANEL_RAISED
BUTTON_PRESSED = SURFACE
BUTTON_DISABLED = '#f8f8f8'
BUTTON_DEFAULT = ACCENT
BUTTON_DEFAULT_HOVER = ACCENT_HOVER

SCROLLBAR = '#454547'
SCROLLBAR_HOVER = '#4e4e50'

SELECTION = '#334a76'
SELECTION_TEXT = TEXT

TAB_INACTIVE = PLAIN_EDIT
TAB_ACTIVE = PANEL
TAB_ACTIVE_BORDER = BORDER_DARK

TRANSLATED_TABLEVIEW = '#1e1f22'
TRANSLATED_TABLEVIEW_ODD = '#26282e'
TRANSLATED_BAR = '#1e1f22'

VALIDATED_TABLEVIEW = '#35354e'
VALIDATED_TABLEVIEW_ODD = '#434361'
VALIDATED_BAR = '#8585c2'

PROGRESS_TABLEVIEW = '#533453'
PROGRESS_TABLEVIEW_ODD = '#684268'
PROGRESS_BAR = '#cf84cf'

UNVALIDATED_TABLEVIEW = '#592a29'
UNVALIDATED_TABLEVIEW_ODD = '#6f3533'
UNVALIDATED_BAR = '#de6a66'

DIFFERENT_TABLEVIEW = '#563e2b'
DIFFERENT_TABLEVIEW_ODD = '#6b4d36'

PROGRESSBAR = PLAIN_EDIT

EDITOR_LINES = '#26282e'
EDITOR_LINES_TEXT = TEXT_MUTED
EDITOR_LINES_BORDER = BORDER_LIGHT

EDITOR_LINE = '#26282e'
EDITOR_BRACKET = '#43454a'

EDITOR_SIMNAME = '#73bd79'
EDITOR_SIMNAME_BOLD = False

EDITOR_MALE = '#70aeff'
EDITOR_MALE_BOLD = False

EDITOR_FEMALE = '#cf84cf'
EDITOR_FEMALE_BOLD = False

EDITOR_VAR_BOLD = True

EDITOR_TAG = TEXT_MUTED

HEADER = BORDER_LIGHT

FONT_SANS = "Roboto, 'Segoe UI', sans-serif"
FONT_MONOSPACE = "'JetBrains Mono', Consolas, 'Courier New', monospace"
