# -*- coding: utf-8 -*-

SURFACE = '#f7fbff'
PANEL = '#ffffff'
PANEL_ALT = '#edf7f8'
PANEL_RAISED = '#e2f1f4'
BORDER = '#cbdde8'
ACCENT = '#1d74d8'
ACCENT_HOVER = '#155fb4'
MUTED = '#607586'
SUCCESS = '#16845b'
WARNING = '#b8651b'

WINDOW = SURFACE

TEXT = '#172433'
TEXT_DISABLED = '#8b9aad'
TEXT_MUTED = MUTED
TEXT_ERROR = '#c94a4a'

BORDER_LIGHT = BORDER
BORDER_DARK = '#b7cbd8'
BORDER_FOCUS = ACCENT

LINE_EDIT = PANEL
PLAIN_EDIT = PANEL
COMBOBOX = '#f1f8fb'

BUTTON = PANEL_ALT
BUTTON_HOVER = PANEL_RAISED
BUTTON_PRESSED = '#d2e8ee'
BUTTON_DISABLED = PANEL_ALT
BUTTON_DEFAULT = ACCENT
BUTTON_DEFAULT_HOVER = ACCENT_HOVER

SCROLLBAR = '#aec7d6'
SCROLLBAR_HOVER = '#7aa6bd'

SELECTION = '#d7efff'
SELECTION_TEXT = '#0b315f'

TAB_INACTIVE = WINDOW
TAB_ACTIVE = PANEL
TAB_ACTIVE_BORDER = ACCENT

TRANSLATED_TABLEVIEW = '#fff'
TRANSLATED_TABLEVIEW_ODD = '#f1f1f1'
TRANSLATED_BAR = '#fff'

VALIDATED_TABLEVIEW = '#d8eafa'
VALIDATED_TABLEVIEW_ODD = '#cde3f6'
VALIDATED_BAR = '#7db8ee'

PROGRESS_TABLEVIEW = '#fff0d9'
PROGRESS_TABLEVIEW_ODD = '#ffe6c2'
PROGRESS_BAR = '#f3a953'

UNVALIDATED_TABLEVIEW = '#ffe0de'
UNVALIDATED_TABLEVIEW_ODD = '#ffd4d1'
UNVALIDATED_BAR = '#ee7d78'

DIFFERENT_TABLEVIEW = '#f8e4cf'
DIFFERENT_TABLEVIEW_ODD = '#f2d8bd'

PROGRESSBAR = BUTTON_HOVER

EDITOR_LINES = '#f1f1f1'
EDITOR_LINES_TEXT = '#b0b0b0'
EDITOR_LINES_BORDER = None

EDITOR_LINE = WINDOW
EDITOR_BRACKET = BUTTON_PRESSED

EDITOR_SIMNAME = '#16845b'
EDITOR_SIMNAME_BOLD = True

EDITOR_MALE = '#1d74d8'
EDITOR_MALE_BOLD = True

EDITOR_FEMALE = '#b0449c'
EDITOR_FEMALE_BOLD = True

EDITOR_VAR_BOLD = True

EDITOR_TAG = TEXT_MUTED

HEADER = '#fff'

FONT_SANS = "Roboto, 'Segoe UI', sans-serif"
FONT_MONOSPACE = "'JetBrains Mono', Consolas, 'Courier New', monospace"
