# -*- coding: utf-8 -*-

SURFACE = '#f5f6f8'
PANEL = '#ffffff'
PANEL_ALT = '#eef1f5'
PANEL_RAISED = '#e7ebf1'
BORDER = '#d7dce4'
ACCENT = '#2563eb'
ACCENT_HOVER = '#1d4ed8'
MUTED = '#697386'
SUCCESS = '#1f8f4d'
WARNING = '#a66a00'

WINDOW = SURFACE

TEXT = '#1f2937'
TEXT_DISABLED = '#9aa3b2'
TEXT_MUTED = MUTED
TEXT_ERROR = '#de6a66'

BORDER_LIGHT = BORDER
BORDER_DARK = '#c7ced8'
BORDER_FOCUS = ACCENT

LINE_EDIT = PANEL
PLAIN_EDIT = PANEL
COMBOBOX = PANEL_ALT

BUTTON = PANEL_ALT
BUTTON_HOVER = PANEL_RAISED
BUTTON_PRESSED = '#dce3ed'
BUTTON_DISABLED = PANEL_ALT
BUTTON_DEFAULT = ACCENT
BUTTON_DEFAULT_HOVER = ACCENT_HOVER

SCROLLBAR = '#c1c1c1'
SCROLLBAR_HOVER = '#929292'

SELECTION = '#dbeafe'
SELECTION_TEXT = '#102a56'

TAB_INACTIVE = WINDOW
TAB_ACTIVE = PANEL
TAB_ACTIVE_BORDER = ACCENT

TRANSLATED_TABLEVIEW = '#fff'
TRANSLATED_TABLEVIEW_ODD = '#f1f1f1'
TRANSLATED_BAR = '#fff'

VALIDATED_TABLEVIEW = '#cecee7'
VALIDATED_TABLEVIEW_ODD = '#c2c2e0'
VALIDATED_BAR = '#c2c2e0'

PROGRESS_TABLEVIEW = '#eccdec'
PROGRESS_TABLEVIEW_ODD = '#e7c1e7'
PROGRESS_BAR = '#e7c1e7'

UNVALIDATED_TABLEVIEW = '#f2c3c2'
UNVALIDATED_TABLEVIEW_ODD = '#eeb4b2'
UNVALIDATED_BAR = '#eeb4b2'

DIFFERENT_TABLEVIEW = '#efd7c4'
DIFFERENT_TABLEVIEW_ODD = '#eaccb5'

PROGRESSBAR = BUTTON_HOVER

EDITOR_LINES = '#f1f1f1'
EDITOR_LINES_TEXT = '#b0b0b0'
EDITOR_LINES_BORDER = None

EDITOR_LINE = WINDOW
EDITOR_BRACKET = BUTTON_PRESSED

EDITOR_SIMNAME = '#388f21'
EDITOR_SIMNAME_BOLD = True

EDITOR_MALE = '#0057ad'
EDITOR_MALE_BOLD = True

EDITOR_FEMALE = '#914c9c'
EDITOR_FEMALE_BOLD = True

EDITOR_VAR_BOLD = True

EDITOR_TAG = TEXT_MUTED

HEADER = '#fff'

FONT_SANS = "Roboto, 'Segoe UI', sans-serif"
FONT_MONOSPACE = "'JetBrains Mono', Consolas, 'Courier New', monospace"
