# -*- coding: utf-8 -*-

APP_VERSION = '2.2.6'
APP_RELEASE_CANDITATE = False
DICTIONARY_VERSION = 4

APP_NAME = 'The Sims 4 Translator Plus'
APP_SHORT_NAME = 'Translator Plus'
APP_UPSTREAM_NAME = 'The Sims 4 Translator'
APP_FORK_URL = 'https://github.com/anhtahaylove/sims4-translator'
APP_UPSTREAM_URL = 'https://github.com/voky1/sims4-translator'
APP_LICENSE = 'MIT'
APP_DISCLAIMER = (
    'Community-maintained fork of voky1/sims4-translator. '
    'Not affiliated with Electronic Arts, Maxis, The Sims, or the upstream maintainer.'
)

COLUMN_MAIN_INDEX = 1
COLUMN_MAIN_ID = 2
COLUMN_MAIN_INSTANCE = 3
COLUMN_MAIN_GROUP = 4
COLUMN_MAIN_SOURCE = 5
COLUMN_MAIN_TRANSLATE = 6
COLUMN_MAIN_COMMENT = 7
COLUMN_MAIN_FLAG = 8

COLUMN_DICTIONARIES_PACKAGE = 1
COLUMN_DICTIONARIES_SOURCE = 2
COLUMN_DICTIONARIES_TRANSLATE = 3
COLUMN_DICTIONARIES_LENGTH = 4

RECORD_MAIN_INDEX = 0
RECORD_MAIN_ID = 1
RECORD_MAIN_INSTANCE = 2
RECORD_MAIN_GROUP = 3
RECORD_MAIN_SOURCE = 4
RECORD_MAIN_TRANSLATE = 5
RECORD_MAIN_FLAG = 6
RECORD_MAIN_RESOURCE = 7
RECORD_MAIN_RESOURCE_ORIGINAL = 8
RECORD_MAIN_PACKAGE = 9
RECORD_MAIN_SOURCE_OLD = 10
RECORD_MAIN_TRANSLATE_OLD = 11
RECORD_MAIN_INDEX_ALT = 12
RECORD_MAIN_COMMENT = 13
RECORD_MAIN_OCCURRENCES = 14

RECORD_DICTIONARY_PACKAGE = 0
RECORD_DICTIONARY_SOURCE = 1
RECORD_DICTIONARY_TRANSLATE = 2
RECORD_DICTIONARY_LENGTH = 3

FLAG_UNVALIDATED = 0
FLAG_PROGRESS = 1
FLAG_VALIDATED = 2
FLAG_TRANSLATED = 3
FLAG_REPLACED = 4

SEARCH_IN_SOURCE = 0
SEARCH_IN_DESTINATION = 1
SEARCH_IN_ID = 2
SEARCH_IN_ALL = 3
SEARCH_CONTAINS = 4
SEARCH_EXACT = 5
SEARCH_BEGINS_WITH = 6
SEARCH_ENDS_WITH = 7
SEARCH_REGEX = 8

NUMERATION_STANDART = 0
NUMERATION_SOURCE = 1
NUMERATION_XML = 2
NUMERATION_XML_DP = 3

EXPORT_STBL = 0
EXPORT_XML = 1
EXPORT_XML_DP = 2
EXPORT_JSON_S4S = 3
EXPORT_BINARY_S4S = 4
EXPORT_HUB_CSV = 5
